{
 "title": "Inference - Faster v1",
 "time": { "from": "now - 1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Model Creator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Select pattern",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"elbow_joint\" or r[\"_field\"] == \"shoulder_lift_joint\" or r[\"_field\"] == \"shoulder_pan_joint\" or r[\"_field\"] == \"wrist_1_joint\" or r[\"_field\"] == \"wrist_2_joint\" or r[\"_field\"] == \"wrist_3_joint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Model Creator",
   "type": "text",
   "gridPos": { "h": 22, "w": 8, "x": 0, "y": 15 },
   "options": {
    "content": "<iframe src=\"http://127.0.0.1:5001/models/create/\" style=\"aspect-ratio: 16 / 8; height: 100%; width: 100%;\" title=\"Model Creator\"></iframe>"
   }
  },
  {
   "title": "Auto training set up",
   "type": "text",
   "gridPos": { "h": 22, "w": 8, "x": 8, "y": 15 },
   "options": {
    "content": "<iframe src=\"http://127.0.0.1:5001/models/auto train/\" style=\"aspect-ratio: 16 / 8; height: 100%; width: 100%;\" title=\"Auto training\"></iframe>"
   }
  },
  {
   "title": "Load Model",
   "type": "text",
   "gridPos": { "h": 22, "w": 8, "x": 16, "y": 15 },
   "options": {
    "content": "<iframe src=\"http://127.0.0.1:5001/models/select/\" style=\"aspect-ratio: 16 / 8; height: 100%; width: 100%;\" title=\"Iframe Example\"></iframe>\n"
   }
  },
  { "title": "Anomaly Detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "All Joints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"elbow_joint\" or r[\"_field\"] == \"shoulder_lift_joint\" or r[\"_field\"] == \"shoulder_pan_joint\" or r[\"_field\"] == \"wrist_1_joint\" or r[\"_field\"] == \"wrist_2_joint\" or r[\"_field\"] == \"wrist_3_joint\" or r[\"_field\"] == \"anomaly_elbow_joint\" or r[\"_field\"] == \"anomaly_shoulder_lift_joint\" or r[\"_field\"] == \"anomaly_shoulder_pan_joint\" or r[\"_field\"] == \"anomaly_wrist_1_joint\" or r[\"_field\"] == \"anomaly_wrist_2_joint\" or r[\"_field\"] == \"anomaly_wrist_3_joint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Inference toggle",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 38 },
   "options": {
    "content": "<iframe src=\"http://127.0.0.1:5001/models/toggle/\" style=\"aspect-ratio: 16 / 8; height: 100%; width: 100%;\" title=\"Toggle\"></iframe>"
   }
  },
  {
   "title": "Last number of anomalies",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"anomalies\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Elbow Joint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"difference_elbow_joint\" or r[\"_field\"] == \"elbow_joint\" or r[\"_field\"] == \"anomaly_elbow_joint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Shoulder Lift Joint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"difference_shoulder_lift_joint\" or r[\"_field\"] == \"shoulder_lift_joint\" or r[\"_field\"] == \"anomaly_shoulder_lift_joint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Shoulder Pan Joint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"difference_shoulder_pan_joint\" or r[\"_field\"] == \"shoulder_pan_joint\" or r[\"_field\"] == \"anomaly_shoulder_pan_joint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Wrist 1 Joint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"difference_wrist_1_joint\" or r[\"_field\"] == \"wrist_1_joint\" or r[\"_field\"] == \"anomaly_wrist_1_joint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Wrist 2 Joint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"difference_wrist_2_joint\" or r[\"_field\"] == \"wrist_2_joint\" or r[\"_field\"] == \"anomaly_wrist_2_joint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Wrist 3 Joint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"London\")\n  |> filter(fn: (r) => r[\"_field\"] == \"difference_wrist_3_joint\" or r[\"_field\"] == \"wrist_3_joint\" or r[\"_field\"] == \"anomaly_wrist_3_joint\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "User usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "System usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Robots\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}